### ISSUE TITLE
pogo_async.exceptions.AuthException: Unable to login or get error information. (timeout?)

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#100]
I was having some (not many, but some) timeouts around at that time, so that apparently is the cause
```
[2017-02-14 09:18:11][ WARNING][worker-112] RPC request timed out.
[2017-02-14 09:18:25][   ERROR][overseer] An exception occurred in try_point
Traceback (most recent call last):
  File "/home/develop/productiv/monocle/worker.py", line 788, in visit
    return await self.visit_point(point, bootstrap=bootstrap)
  File "/home/develop/productiv/monocle/worker.py", line 899, in visit_point
    responses = await self.call(request)
  File "/home/develop/productiv/monocle/worker.py", line 722, in call
    raise err
  File "/home/develop/productiv/monocle/worker.py", line 653, in call
    response = await request.call()
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/pgoapi.py", line 181, in call
    response = await request.request(self._api_endpoint, self._req_method_list, self._position)
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/rpc_api.py", line 159, in request
    except Exception:
pogo_async.exceptions.NotLoggedInException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/auth_ptc.py", line 110, in user_login
    self._refresh_token = qs['ticket'][0]
KeyError: 'ticket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/auth_ptc.py", line 118, in user_login
    if j.get('error_code') == 'users.login.activation_required':
AttributeError: 'NoneType' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/develop/productiv/monocle/overseer.py", line 585, in try_point
    if await worker.visit(point):
  File "/home/develop/productiv/monocle/worker.py", line 792, in visit
    if not await self.login(reauth=True):
  File "/home/develop/productiv/monocle/worker.py", line 175, in login
    timeout=config.LOGIN_TIMEOUT
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/pgoapi.py", line 81, in set_authentication
    if not await self._auth_provider.user_login(username, password):
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/auth_ptc.py", line 123, in user_login
    raise AuthException('Unable to login or get error information.') from e
pogo_async.exceptions.AuthException: Unable to login or get error information.
```

**Comment by Noctem** [comment]
Is this still happening?
