### ISSUE TITLE
Not enough Workers error when running scan.py

### ISSUE THREAD

**Issue by krasatusya** [Noctem/Monocle#109]
Hello, 
I followed instructions up to the running scan.py 
I replaced the fake Accounts with 4 real accounts and trying to run scan.py and getting the following error.

Could you please help me  to resolve this issue.
Thanks

========================================================================
$ python3 scan.py
Traceback (most recent call last):
  File "/Users/XXXX/Documents/pokemon/Monocle/monocle/worker.py", line 89, in __init__
    self.account = self.extra_queue.get_nowait()
  File "<string>", line 2, in get_nowait
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXX/Documents/pokemon/Monocle/monocle/worker.py", line 92, in __init__
    self.account = self.captcha_queue.get_nowait()
  File "<string>", line 2, in get_nowait
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scan.py", line 295, in <module>
    main()
  File "scan.py", line 251, in main
    overseer.start()
  File "/Users/XXXX/Documents/pokemon/Monocle/monocle/overseer.py", line 93, in start
    self.workers = tuple(Worker(worker_no=x) for x in range(self.count))
  File "/Users/XXXX/Documents/pokemon/Monocle/monocle/overseer.py", line 93, in <genexpr>
    self.workers = tuple(Worker(worker_no=x) for x in range(self.count))
  File "/Users/XXXX/Documents/pokemon/Monocle/monocle/worker.py", line 94, in __init__
    raise ValueError("You don't have enough accounts for the number of workers specified in GRID.") from e
ValueError: You don't have enough accounts for the number of workers specified in GRID.

**Comment by stunnaspinz** [comment]
If your only using 4 accounts. Make sure to adjust the grid in config.py
GRID = (4, 4)  # rows, columns

If you only have 4 accounts it should look like 
GRID = (2, 2)  # rows, columns

**Comment by krasatusya** [comment]
@stunnaspinz
Thanks for the answer, I changed to (2, 2) and it accepted it.
Thanks
