### ISSUE TITLE
ClientTimeoutError

### ISSUE THREAD

**Issue by n30nl1ght** [Noctem/Monocle#119]
```
Traceback (most recent call last):
  File "/home/pokego/MonocleBern/monocle/worker.py", line 646, in visit
    return await self.visit_point(point, bootstrap=bootstrap)
  File "/home/pokego/MonocleBern/monocle/worker.py", line 757, in visit_point
    responses = await self.call(request)
  File "/home/pokego/MonocleBern/monocle/worker.py", line 511, in call
    response = await request.call()
  File "/home/pokego/.local/lib/python3.5/site-packages/pogo_async/pgoapi.py", line 181, in call
    response = await request.request(self._api_endpoint, self._req_method_list, self._position)
  File "/home/pokego/.local/lib/python3.5/site-packages/pogo_async/rpc_api.py", line 168, in request
    self.request_proto = self.request_proto or await self._build_main_request(subrequests, player_position)
  File "/home/pokego/.local/lib/python3.5/site-packages/pogo_async/rpc_api.py", line 242, in _build_main_request
    await self._hash_engine.hash(sig.epoch_timestamp_ms, request.latitude, request.longitude, request.accuracy, ticket_serialized, sig.field22, request.requests)
  File "/home/pokego/.local/lib/python3.5/site-packages/pogo_async/hash_server.py", line 45, in hash
    async with self._session.post(self.endpoint, headers=headers, data=payload, timeout=self.timeout) as resp:
  File "/home/pokego/.local/lib/python3.5/site-packages/aiohttp/client.py", line 587, in __aenter__
    self._resp = yield from self._coro
  File "/home/pokego/.local/lib/python3.5/site-packages/aiohttp/client.py", line 215, in _request
    conn = yield from self._connector.connect(req)
  File "/home/pokego/.local/lib/python3.5/site-packages/pogo_async/connector.py", line 61, in connect
    raise ClientTimeoutError(
NameError: name 'ClientTimeoutError' is not defined
```

I have many if these error in the log.
The pogo_async ist up to date.

**Comment by thordurk91** [comment]
fixed in this commit to pgoapi

https://github.com/Noctem/pgoapi/commit/3753684758b621aeb648042f389ef90e04c5b492

**Comment by n30nl1ght** [comment]
I have the latest PR and the error is not solved!!!

**Comment by thordurk91** [comment]
Does your pogo_async/connector.py have that line from the commit?

**Comment by n30nl1ght** [comment]
Yes

**Comment by n30nl1ght** [comment]
ohh no, it's not included
Strange
i had run pip3 install --user -U -r requirements.txt but the line is not inside connector.py

**Comment by thordurk91** [comment]
try manually updating it by pip3 installing the git from requirements?

**Comment by n30nl1ght** [comment]
I installed the git with
Apt-get install git
