### ISSUE TITLE
MySQL limits? sqlalchemy

### ISSUE THREAD

**Issue by stunnaspinz** [Noctem/Monocle#133]
I have been getting this issue quite frequently lately. I thought it might be outdated, so I pulled fresh copy and ran again.. Same issue. web.py runs fine for a few minutes then these errors start occurring.

[2017-02-23 13:21:39,108] ERROR in app: Exception on /data [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\pool.py", line 112
2, in _do_get
    return self._pool.get(wait, self._timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\util\queue.py", li
ne 156, in get
    raise Empty
sqlalchemy.util.queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1982, in
wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1614, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1517, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, i
n reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1612, in
full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1598, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Pokemoninterface\web.py", line 98, in pokemon_data
    return jsonify(get_pokemarkers(last_id))
  File "C:\Pokemoninterface\monocle\web_utils.py", line 105, in get_pokemarkers
    pokemons = db.get_sightings(session, after_id)
  File "C:\Pokemoninterface\monocle\db.py", line 622, in get_sightings
    Sighting.id > after_id \
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\query.py", lin
e 2638, in all
    return list(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\query.py", lin
e 2790, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\query.py", lin
e 2811, in _execute_and_instances
    close_with_result=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\query.py", lin
e 2820, in _get_bind_args
    **kw
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\query.py", lin
e 2802, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\session.py", l
ine 966, in connection
    execution_options=execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\session.py", l
ine 971, in _connection_for_bind
    engine, execution_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\orm\session.py", l
ine 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\engine\base.py", l
ine 2103, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\engine\base.py", l
ine 2138, in _wrap_pool_connect
    return fn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\pool.py", line 387
, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\pool.py", line 766
, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\pool.py", line 516
, in checkout
    rec = pool._do_get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlalchemy\pool.py", line 113
1, in _do_get
    (self.size(), self.overflow(), self._timeout))
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30

My setup may be overkill but here it is:

Server 1. HAProxy (load balancing) (ubuntu 16)
Server 2. MySQL database (Windows 2012 R2) (Quadcore 8GB ram)
Server 3  Scan and Web (Windows 2012 R2) (Quadcore 8GB ram)
Server 4  Scan and Web (Windows 2012 R2) (Quadcore 8GB ram)

I tried looking over ways to attempt to increase the pool_size but when i make the changes that I can see it breaks completely. 

while these errors are occurring the map still shows active, but will not load any new pokemon to the map.

**Comment by stunnaspinz** [comment]
I added a second network interface and setup a private network for the scan.py to send data to mysql over. The web.py (in seperate folder using its own config.py) connects to pull data off seperate network interface and it seems to have resolved the issue. 750 users and large scanning area appears to have created some form of bottle neck.. :)
