### ISSUE TITLE
KeyError: 'username'

### ISSUE THREAD

**Issue by ibuckshot5** [Noctem/Monocle#162]
Whenever I try to load my 400 accounts into Monocle, it returns this error:
`Traceback (most recent call last):
  File "scan.py", line 28, in <module>
    from monocle.shared import LOOP, get_logger, SessionManager, ACCOUNTS
  File "C:\Users\ibuckshot\Monocle\monocle\shared.py", line 12, in <module>
    ACCOUNTS = load_accounts()
  File "C:\Users\ibuckshot\Monocle\monocle\utils.py
", line 364, in load_accounts
    accounts = load_accounts_csv()
  File "C:\Users\ibuckshot\Monocle\monocle\utils.py
", line 387, in load_accounts_csv
    accounts[row['username']] = dict(row)
KeyError: 'username'`

My accounts.csv file is setup like this:
`username,password`
`username2,password2`

Does anyone have any idea as to what this is?

**Comment by skateskate** [comment]
Did you accidentally delete the first row of the .csv file? Don't forget also the provider you are using (i.e. ptc or google). Your .csv should look like this:

```
username,password,provider,model,iOS,id
user1,password1,ptc
user2,password2,ptc
```
Hope this helps.

**Comment by ibuckshot5** [comment]
Great, I got past that, but now it throws this error:

`Traceback (most recent call last):
  File "scan.py", line 222, in <module>
    main()
  File "scan.py", line 207, in main
    overseer.start()
  File "C:\Users\Alex\Downloads\Monocle-develop\Monocle-develop\monocle\overseer
.py", line 92, in start
    self.workers = tuple(Worker(worker_no=x) for x in range(self.count))
  File "C:\Users\Alex\Downloads\Monocle-develop\Monocle-develop\monocle\overseer
.py", line 92, in <genexpr>
    self.workers = tuple(Worker(worker_no=x) for x in range(self.count))
  File "C:\Users\Alex\Downloads\Monocle-develop\Monocle-develop\monocle\worker.p
y", line 103, in __init__
    self.initialize_api()
  File "C:\Users\Alex\Downloads\Monocle-develop\Monocle-develop\monocle\worker.p
y", line 118, in initialize_api
    device_info = get_device_info(self.account)
  File "C:\Users\Alex\Downloads\Monocle-develop\Monocle-develop\monocle\utils.py
", line 206, in get_device_info
    if account['iOS'].startswith('1'):
AttributeError: 'NoneType' object has no attribute 'startswith'`

(I'm using Python 3.6)

**Comment by Noctem** [comment]
@ibuckshot5 Update or delete your *accounts.pickle*. That shouldn't happen on the latest version.
