### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'user_login'

### ISSUE THREAD

**Issue by tdguchi** [Noctem/Monocle#166]
[2017-03-06 19:21:44][   ERROR][worker-3] A wild AttributeError appeared!
Traceback (most recent call last):
  File "C:\Users\pablo\Monocle\monocle\worker.py", line 605, in visit
    await self.login()
  File "C:\Users\pablo\Monocle\monocle\worker.py", line 157, in login
    timeout=conf.LOGIN_TIMEOUT
  File "C:\Users\pablo\AppData\Local\Programs\Python\Python36\lib\site-packages\aiopogo\pgoapi.py", line 49, in set_authentication
    if not await self._auth_provider.user_login(username, password):
AttributeError: 'NoneType' object has no attribute 'user_login'

how can i fix it? thanks

**Comment by Noctem** [comment]
Fixed in d3ecb6b5d89e61463bf38915059c28614e9abfe4.
