### ISSUE TITLE
ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by cyanosis78** [Noctem/Monocle#171]
I get this error every now and then, what could be wrong?

Exiting, please wait until all tasks finish
Finishing tasks...
Dumping pickles...
Updating spawns pickle...
Closing pipes, sessions, and event loop...
Done.
Traceback (most recent call last):
  File "scan.py", line 223, in <module>
    main()
  File "scan.py", line 215, in main
    LOOP.run_until_complete(launcher)
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

[2017-03-08 16:37:53][   ERROR][cleanup] A wild ValueError appeared during exit!
Traceback (most recent call last):
  File "scan.py", line 215, in main
    LOOP.run_until_complete(launcher)
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\DavidJohn\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

**Comment by DavePlater** [comment]
Are you triggering the exist and THEN an exception occurs, or is the exception causing the exit?

**Comment by cyanosis78** [comment]
the exception is causing the exit.

**Comment by stunnaspinz** [comment]
I get something similar to this but the line above "Exiting, please wait until all tasks finish" says that my hash key(s) expired.. Even when the keys are still valid and checked properly.

**Comment by DavePlater** [comment]
I run a few copies of scan.py (different directories) and ONE of them was frequently exiting with the "Hash expired" message. All my copies use the same hash key though.

**Comment by stunnaspinz** [comment]
@DavePlater my setup is the same. I have 8 instances running from 8 different directories (different areas of town).  and periodically one or two of them exit that way.. Not sure why.. But the keys are valid (I am using multihash as I have two keys in use to balance between all instances). I expect it to fail when the hash key is expired but not before hand with false info.. Good thing is its easily restarted, just a pain to have to do it if the key is not in fact expired.
