### ISSUE TITLE
[CRIT] `TypeError: 'NoneType' object is not callable` on spawns.update()

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#190]
monocle is not scanning because of the following error
```
[2017-03-20 01:35:23][    INFO][root] -------------------------------------
[2017-03-20 01:35:23][    INFO][root] Starting up!
[2017-03-20 01:35:23][ WARNING][spawns] Obsolete or invalid spawns pickle type, reloading from DB.
[2017-03-20 01:35:36][   ERROR][overseer] A wild TypeError appeared while updating spawns!
Traceback (most recent call last):
  File "/home/develop/pokeminer/monocle/overseer.py", line 357, in update_spawns
    await run_threaded(spawns.update())
  File "/home/develop/pokeminer/monocle/shared.py", line 72, in run_threaded
    return await LOOP.run_in_executor(x, cb, *args)
  File "/usr/lib64/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable
```
the error is repeated every few seconds

**Comment by evenly-epic-mule** [comment]
https://github.com/Noctem/Monocle/commit/e1b97f1cdbf085c406346c0e702c955eea6688d9 fixed
