### ISSUE TITLE
Hash Key needed?

### ISSUE THREAD

**Issue by Nico1300** [Noctem/Monocle#195]
Hey Guys :D Sorry its me again. After many hours of work i'm still getting this error AttributeError: HASH_KEY not in config, and no default has been set.
The config says that you don't need an Hash key?!

**Comment by Nico1300** [comment]
Here's the full error    Win10 /
C:\Users\Nico\Desktop\map\Monocle>py create_db.py

C:\Users\Nico\Desktop\map\Monocle>py scan.py
Traceback (most recent call last):
  File "C:\Users\Nico\Desktop\map\Monocle\monocle\sanitized.py", line 259, in __getattr__
    default = _defaults.pop(name)
KeyError: 'HASH_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scan.py", line 225, in <module>
    main()
  File "scan.py", line 212, in main
    activate_hash_server(conf.HASH_KEY)
  File "C:\Users\Nico\Desktop\map\Monocle\monocle\sanitized.py", line 265, in __getattr__
    raise AttributeError(err)
AttributeError: HASH_KEY not in config, and no default has been set.

**Comment by stunnaspinz** [comment]
You need a hash key.. Niantic / Nintendo closed the free API that was being used.

**Comment by Nico1300** [comment]
ok thank you :/
