### ISSUE TITLE
AttributeError: Landmark object has no attribute south

### ISSUE THREAD

**Issue by mewio** [Noctem/Monocle#208]
A recent update from the develop branch broke notifications for me. scan.log shows messages like this:

    [   ERROR][eventloop] {'future': <Task finished coro=<Notifier.notify() done, defined at /home/ubuntu/ap/monocle/monocle/notification.py:679> exception=AttributeError("'Landmark' object has no attribute 'south'",)>, 'exception': AttributeError("'Landmark' object has no attribute 'south'",), 'message': 'Task exception was never retrieved'}

Here's a stack trace:

    $ scripts/test_notifications.py -i 16 
    Traceback (most recent call last):
      File "scripts/test_notifications.py", line 113, in <module>
        if loop.run_until_complete(notifier.notify(pokemon, randint(1, 2))):
      File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
        return future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/home/ubuntu/ap/monocle/monocle/notification.py", line 755, in notify
        notified = await Notification(pokemon, iv_score, time_of_day).notify()
      File "/home/ubuntu/ap/monocle/monocle/notification.py", line 298, in notify
        self.landmark = conf.LANDMARKS.find_landmark(self.coordinates)
      File "/home/ubuntu/ap/monocle/monocle/landmarks.py", line 204, in find_landmark
        landmark = find_within(self.points_of_interest, coords)
      File "/home/ubuntu/ap/monocle/monocle/landmarks.py", line 230, in find_within
        within = [landmark for landmark in landmarks if coordinates in landmark]
      File "/home/ubuntu/ap/monocle/monocle/landmarks.py", line 230, in <listcomp>
        within = [landmark for landmark in landmarks if coordinates in landmark]
      File "/home/ubuntu/ap/monocle/monocle/landmarks.py", line 73, in __contains__
        if (self.south <= lat <= self.north and
    AttributeError: 'Landmark' object has no attribute 'south'

Looks like it comes from the __contains__() implementation in e9582288409b00c7d6b2e8b0c96e5e4afe3d726e.

The landmark it's choking on was defined like this:
    LANDMARKS.add("Landmark Name", shortname="Landmark", points=((123.4567, 123.4567),))

**Comment by mewio** [comment]
Turns out this is a side-effect of upgrading with pickled landmarks from before commit e9582288409b00c7d6b2e8b0c96e5e4afe3d726e. Workaround: run `pickle_landmarks.py` again.

Now that I know this, avoiding the problem is easy, but it would have been nice to get an informative error message instead of spending my time troubleshooting it, and to have the problem appear at startup time instead of later in the day when I'm nowhere near the machine and unable to access the log file.

Possible enhancement: Pickled object versioning w/ error messages for old pickles at startup time.
