### ISSUE TITLE
SSL trouble with twitter API

### ISSUE THREAD

**Issue by kekel87** [Noctem/Monocle#209]
I tried to send twitter notification from my server.

It work great on my local computer with the script test_notifications.py, but I’ve got an exception when I try it from my server.

Here an example of error:
```
Traceback (most recent call last):
  File "/usr/src/app/monocle/notification.py", line 534, in tweet
    display_coordinates=True)
  File "/usr/local/lib/python3.6/site-packages/peony/utils.py", line 130, in decorated_request
    return await request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/peony/client.py", line 269, in request
    async with session.request(**req_kwargs) as response:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 595, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host api.twitter.com:443 ssl:True [Can not connect to api.twitter.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)]]

```

If it help, my server use HTTPS (with Let's-Encrypt) and the app (scan.py and web.py) is running inside a Docker container.

Thank you.

**Comment by kekel87** [comment]
Also, I can't make pycairo functional.



I tried to install it via pip (as suggested by optional-requirements.txt) :
`pip install pycairo>=1.10.0`
But I got the message :
```python
Could not find a version that satisfies the requirement pycairo (from versions: )
No matching distribution found for pycairo
```



In the wiki I found instructions for Debian :
`apt-get install python3-cairo`
Installation is ok, but when I try to import cairo with
`python -c "import cairo"`
I've got :
`ModuleNotFoundError: No module named 'cairo'`



As you recommend, I use python 3.6, but I was wondering if this library is suitable for this version, because other people in topics seems to have similar problems.

Any idea?



Thanks.

**Comment by emikulic** [comment]
Try: `pip3 install https://github.com/pygobject/pycairo/releases/download/v1.15.4/pycairo-1.15.4.tar.gz
`

Per https://lists.cairographics.org/archives/cairo/2017-June/028155.html
