### ISSUE TITLE
web.py: early call to render_map() fails

### ISSUE THREAD

**Issue by mewio** [Noctem/Monocle#228]
Since commit a2e3c61b2ddd7772ae3c62a6f252476cce0e804b, running web.py fails to start:

    $ ./web.py
    Traceback (most recent call last):
      File "./web.py", line 78, in <module>
        def fullmap(map_html=render_map()):
      File "./web.py", line 62, in render_map
        extra_css_js=Markup(css_js)
      File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/templating.py", line 132, in render_template
        ctx.app.update_template_context(context)
    AttributeError: 'NoneType' object has no attribute 'app'

**Comment by mewio** [comment]
This commit is also a missing comma

**Comment by mewio** [comment]
This commit is also [missing a comma](https://github.com/Noctem/Monocle/commit/a2e3c61b2ddd7772ae3c62a6f252476cce0e804b#diff-3e888358e6ca590256579ee0e54b4eddR186) in the report_single() definition.
