### ISSUE TITLE
"Error occured in launcher loop"

### ISSUE THREAD

**Issue by Jabsu** [Noctem/Monocle#241]
After one of the latest updates, I've started to get these:

[2017-04-20 18:59:58][   ERROR][overseer] Error occured in launcher loop.
Traceback (most recent call last):
  File "...\overseer.py", line 364, in launch
    await self._launch(update_spawns)
  File "...\overseer.py", line 396, in _launch
    for point, (spawn_id, spawn_seconds) in spawns_iter:
TypeError: 'NoneType' object is not iterable

The scanner will always forcibly close after these. Maybe something to do with the database? I'm using MySQL and made a new database just to be sure, but the problem still exists.

**Comment by leald95** [comment]
Same thing is happening with me while using Postgres, thought I was the only one.

**Comment by Jabsu** [comment]
I removed the spawns.pickle file and now the problem seems to be gone.

**Comment by leald95** [comment]
I changed a few config settings around that had to do with spawns and altitude and what not, and it seems to be working for now, but I will try that next if it happens again. Thank you.

**Comment by patienttrainer** [comment]
Same here. Same setup. Same solution.

**Comment by steffenkopa** [comment]
Seems to happen again and again. Deleting spawns.pickle only solves it temporarily

**Comment by Jabsu** [comment]
I haven't had the problem anymore. I'm not familiar enough with the code to say for sure, but I guess it has something to do with unknown spawns that are out of reach (outside of map boundaries, e.g. when using polygons).  By removing the spawns.pickle file, those out-of-reach spawns are gone from the workers' mind, so they can concentrate on the spawns that matter. This will help (or at least in my case it helped) with skipping, timeouts and clustering too. 

Anyway, I hope this will get some attention, as it's pretty critical.

**Comment by mewio** [comment]
Has anyone tried running scan.py --bootstrap instead of deleting spawns.pickle? I had a `'NoneType' object is not iterable` crash yesterday, and that solved it. Not sure if it was the same place in the code as described in this bug report, though.

**Comment by ghost** [comment]
This crash has been happening to me a lot since the increased event spawns arrived. Running scan.py --bootstrap does temporarily work around it without having to delete spawns.pickle.

**Comment by ghost** [comment]
I believe the cause is [this line](https://github.com/Noctem/Monocle/commit/c06018b9e4a4739b2661abbdc5e3a25fee50f4b5#diff-d8f60b4ee0bad02def8fcb9273b6e4f3R160) in MoreSpawns.add_known():

    # add so that have_point() will be up to date
    self.known[point] = None

The overseer code expects the `known` dict to contain (spawn-id, spawn-time) tuples. When it finds `None` instead, it breaks.

**Comment by DavePlater** [comment]
I was getting this frequently up until a few weeks ago when I updated everything (requirements and monocole). The fix had always been to delete the pickle.
