### ISSUE TITLE
Trying to use a google account: AttributeError: 'AuthGoogle' object has no attribute '_username'

### ISSUE THREAD

**Issue by originalstocksy** [Noctem/Monocle#242]
I am running Monocle for the first time and it never finishes bootstrapping.  In the logs I can see:

```
[2017-04-21 10:22:57][   ERROR][worker-0] A wild AttributeError appeared!
Traceback (most recent call last):
  File "/home/myuser/Monocle/monocle/worker.py", line 604, in visit
    await self.login()
  File "/home/myuser/Monocle/monocle/worker.py", line 161, in login
    timeout=conf.LOGIN_TIMEOUT
  File "/home/myuser/.pyenv/versions/general/lib/python3.6/site-packages/aiopogo/pgoapi.py", line 40, in set_authentication
    await self.auth_provider.user_login(username, password)
  File "/home/myuser/.pyenv/versions/general/lib/python3.6/site-packages/aiopogo/auth_google.py", line 27, in user_login
    assert isinstance(self._username, str) and isinstance(self._password, str)
AttributeError: 'AuthGoogle' object has no attribute '_username'
```

I have created a Pokémon go user through Google and used it to log in to the game.  My accounts.csv contains just this one Google account like so:

```
username,password,provider,model,iOS,id
mypogousername,mypassword,google
```

What am I doing wrong?

**Comment by manolomanila** [comment]
> mypogousername

It has to be your account username in order to log in.

I only have PTC accounts but I tried using a google account and got a similar error. I've tried these:

```
username,password,provider,model,iOS,id
mymail@gmail.com,mypassword,google,,,
```
```
username,password,provider,model,iOS,id
mymail,mypassword,google,,,
```

**Comment by originalstocksy** [comment]
Thanks for responding.  I tried using the email address as the account name, just the bit before the @ symbol, in double quotes, not in double quotes... no luck!

In the end I created a Pokémon Trainers Club account instead and that is working, so I'm happy.

**Comment by windblow** [comment]
This issue is happening because of a bug on PGOAPI, which is installed as a requirement. I peeked at the repository for Pgoapi and it seems the bug is corrected on the WIP branch, but still haven't made it to master release. 

In the meantime, I did some corrections directly to the scripts that python import as a requirement for Nocturne and got Google Accounts working again. You need to find the following python scripts on your machine and edit them in the following way:

1. pgoapi.py
   change line 44 from:
```
        self.auth_provider = AuthGoogle(proxy=proxy, refresh_token=refresh_token)
```
   to (remember to use exactly 4 spaces for identation since this is how Python infers instruction blocks):
```
        try:
            self.auth_provider = AuthGoogle(proxy=proxy, refresh_token=refresh_token)
        except NameError:
            self.auth_provider = AuthGoogle(proxy=self._proxy, refresh_token=refresh_token)
```

2. auth_google.py:
   change line 27 from:
```
        assert isinstance(self._username, str) and isinstance(self._password, str)
```
   to:
```
        assert isinstance(username, str) and isinstance(password, str)`
```
   And then change line 66 on the same file from:
```
        self._access_token_expiry = token_data['Expiry']
```
   to:
```
        self._access_token_expiry = float(token_data['Expiry'])
```

That should do the trick.

PS.: Every time you update requirements on Monocle you'll have to edit the files again, at least until the release of pgoapi is updated
