### ISSUE TITLE
scan.py crash

### ISSUE THREAD

**Issue by Splanex** [Noctem/Monocle#245]
After several minutes, the scan.py crash:

`[2017-04-22 00:00:02][   ERROR][overseer] Error occured in launcher loop.
Traceback (most recent call last):
  File "/var/www/Monocle/monocle/overseer.py", line 364, in launch
    await self._launch(update_spawns)
  File "/var/www/Monocle/monocle/overseer.py", line 383, in _launch
    start_point = self.get_start_point()
  File "/var/www/Monocle/monocle/overseer.py", line 319, in get_start_point
    for spawn_id, spawn_time in spawns.known.values():
TypeError: 'NoneType' object is not iterable`

**Comment by Jabsu** [comment]
Delete spawns.pickle file and start again. Ref: #241
