### ISSUE TITLE
Issue with requirements .txt and pogeo

### ISSUE THREAD

**Issue by Tpixelminer** [Noctem/Monocle#254]
So, I'm trying to install requirements.txt on a Raspberry pi running pixel and I'm receiving an error that has to do with the * in the code for pogeo. I'm using python 3.5.1. Any ideas? -Todd

**Comment by Noctem** [comment]
What error?

**Comment by Tpixelminer** [comment]
Hi, sorry it took me so long to respond. Here is the error:

pi@raspberrypi:~/Desktop/Monocle-develop $ pip3 install -r requirements.txt
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'pogeo==0.3.0.*', 'at', '*')

Storing debug log for failure in /home/pi/.pip/pip.log
pi@raspberrypi:~/Desktop/Monocle-develop $

**Comment by DavePlater** [comment]
That looks like you have an outdated copy of the repository, the requirements file has 'pogeo==0.3.*'
Be sure to do a fresh pull of monocle

**Comment by Tpixelminer** [comment]
Ok, thanks for the help. I'll fix it tonight
