### ISSUE TITLE
Issue running scan.py (ValueError)

### ISSUE THREAD

**Issue by jj11ct** [Noctem/Monocle#256]
Hi there,

I am new to python and monocle and enjoying the challenge - but please bare with me on the below as I haven't got a clue on how I can get past the following error to get the map up and running.

Firstly I followed all the steps on the github site, I am running postgresql and have set up all the details in the config.py as per the site.

The error I get right now is when running scan.py is as follows:

c:\Monocle-develop>scan.py
Traceback (most recent call last):
  File "C:\Monocle-develop\monocle\worker.py", line 87, in __init__
    self.account = self.extra_queue.get_nowait()
  File "<string>", line 2, in get_nowait
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\multiproce
ssing\managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Monocle-develop\monocle\worker.py", line 90, in __init__
    self.account = self.captcha_queue.get_nowait()
  File "<string>", line 2, in get_nowait
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\multiproce
ssing\managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Monocle-develop\scan.py", line 218, in <module>
    main()
  File "C:\Monocle-develop\scan.py", line 203, in main
    overseer.start(args.status_bar)
  File "C:\Monocle-develop\monocle\overseer.py", line 92, in start
    self.workers = tuple(Worker(worker_no=x) for x in range(conf.GRID[0] * conf.
GRID[1]))
  File "C:\Monocle-develop\monocle\overseer.py", line 92, in <genexpr>
    self.workers = tuple(Worker(worker_no=x) for x in range(conf.GRID[0] * conf.
GRID[1]))
  File "C:\Monocle-develop\monocle\worker.py", line 92, in __init__
    raise ValueError("You don't have enough accounts for the number of workers s
pecified in GRID.") from e
ValueError: You don't have enough accounts for the number of workers specified i
n GRID.

Now, I initially had 5 accounts and quite a big area, so I reduced the area to a very small area 1-2 houses and added more accounts - I now have 10 accounts in the accounts.csv file.

Any clue as to what I can do to fix the error? perhaps an earlier error/exception is causing this?

Thanks in advance for any assistance, let me know if you need more info on my set up I will happily provide it.

Regards
Jay

**Comment by jj11ct** [comment]
found (and reduced) the GRID variable in the config file : )
