### ISSUE TITLE
viewing map in web (web.py)

### ISSUE THREAD

**Issue by jj11ct** [Noctem/Monocle#257]
Hi there,

When I run web.py - it mentions that it is running on http://0.0.0.0:5000 (local) however I can't seem to access this nor find a way to change this to another output location that is accessible. My scans run successfully on scan.py

I realise that this might be straight forward so I apologize in advance as I am new to this, and do thank you in advance for leading me in the right direction.

Here is the cmd response for trying to run the UI of the scan.
C:\Monocle-develop>web.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

Thanks,
JJ

**Comment by thordurk91** [comment]
Try looking at localhost:5000

web.py -H 0.0.0.0 -P 5000 is the format if you want to change what ip address it binds to and the port

**Comment by jj11ct** [comment]
Thanks! Got it to load in the browser 

I am now however seeing the following:

'Monocle initializing, please wait'

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Lenovo>cd c"\monocle-develop


This is what I see in cmd:

c:\Monocle-develop>web.py
Traceback (most recent call last):
  File "C:\Monocle-develop\web.py", line 15, in <module>
    from monocle import db, sanitized as conf
  File "C:\Monocle-develop\monocle\db.py", line 14, in <module>
    from . import bounds, spawns, db_proc, sanitized as conf
  File "C:\Monocle-develop\monocle\bounds.py", line 4, in <module>
    from .utils import get_distance
  File "C:\Monocle-develop\monocle\utils.py", line 17, in <module>
    from aiopogo import utilities as pgoapi_utils
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\aiopogo\__init__.py", line 29, in <module>
    from .pgoapi import PGoApi
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\aiopogo\pgoapi.py", line 16, in <module>
    from .auth_google import AuthGoogle
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\aiopogo\auth_google.py", line 5, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\Cryptodome\Cipher\AES.py", line 108, in <module>
    _cproto)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    return load_lib(pycryptodome_filename(dir_comps, basename + ext), cdecl)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\Cryptodome\Util\_raw_api.py", line 109, in load_lib
    return CDLL(name)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__i
nit__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
KeyboardInterrupt

c:\Monocle-develop>web.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [16/May/2017 09:36:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2017 09:36:02] "GET /static/css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2017 09:36:02] "GET /static/css/leaflet.css HTTP/1.1" 200
-
127.0.0.1 - - [16/May/2017 09:36:02] "GET /static/css/bootstrap.min.css HTTP/1.1
" 200 -
127.0.0.1 - - [16/May/2017 09:36:03] "GET /static/js/main.js HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2017 09:36:03] "GET /static/js/jquery-3.2.1.min.js HTTP/1.
1" 200 -
127.0.0.1 - - [16/May/2017 09:36:03] "GET /static/img/my-location.png HTTP/1.1"
200 -
127.0.0.1 - - [16/May/2017 09:36:03] "GET /static/img/settings.png HTTP/1.1" 200
 -
127.0.0.1 - - [16/May/2017 09:36:03] "GET /static/js/bootstrap.min.js HTTP/1.1"
200 -
127.0.0.1 - - [16/May/2017 09:36:03] "GET /static/js/leaflet.js HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2017 09:36:04] "GET /static/favicon/favicon-32x32.png HTTP
/1.1" 200 -

Any assistance is greatly appreciated, 

Regards,
Jay
