### ISSUE TITLE
Solve Captchas Issue

### ISSUE THREAD

**Issue by jj11ct** [Noctem/Monocle#260]
HI there, 

could someone assist me with getting manual solve captchas to work correctly?

I'm using Selenium 3.0
Chromewebdriver 2.29 (latest)

c:\Mono>solve_captchas.py
Traceback (most recent call last):
  File "C:\Mono\solve_captchas.py", line 168, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\asyncio\ba
se_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Mono\solve_captchas.py", line 58, in main
    manager.connect()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\multiproce
ssing\managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\multiproce
ssing\connection.py", line 485, in Client
    c = PipeClient(address)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36-32\lib\multiproce
ssing\connection.py", line 686, in PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] The system cannot find the file specified

c:\Mono>chromedriver.exe
Starting ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233) on
port 9515
Only local connections are allowed.

Thanks!

**Comment by jj11ct** [comment]
didn't know i had to run scan.py first (doh!)  it worked : )
