### ISSUE TITLE
create_db.py DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by peterchabs** [Noctem/Monocle#272]
Hi, i'm unable to run create_db.py
Running on windows 10
Python 3.6.2
requirements installed successfully.

``` py -3 create_db.py
Traceback (most recent call last):
  File "create_db.py", line 9, in <module>
    from monocle.db import Base, _engine
  File "C:\SCANNER\Monocle\monocle\db.py", line 12, in <module>
    from . import bounds, spawns, db_proc, sanitized as conf
  File "C:\SCANNER\Monocle\monocle\bounds.py", line 4, in <module>
    from .utils import get_distance
  File "C:\SCANNER\Monocle\monocle\utils.py", line 18, in <module>
    from pogeo import get_distance
ImportError: DLL load failed: The specified module could not be found.```

**Comment by peterchabs** [comment]
Solved by installing WinPython.

**Comment by wellington1092** [comment]
Traceback (most recent call last):
  File "create_db.py", line 9, in <module>
    from monocle.db import Base, _engine
  File "C:\SCANNER\Monocle\monocle\db.py", line 12, in <module>
    from . import bounds, spawns, db_proc, sanitized as conf
  File "C:\SCANNER\Monocle\monocle\bounds.py", line 4, in <module>
    from .utils import get_distance
  File "C:\SCANNER\Monocle\monocle\utils.py", line 18, in <module>
    from pogeo import get_distance
ImportError: DLL load failed: The specified module could not be found.

Please, I have the same problem and I already installed Winpython but I still have the same error

**Comment by DavePlater** [comment]
What db type are you configured for? mySQL? sqlite?
You are calling create_db.py from the instance directory via .\scripts\create_db.py correct? And not trying to do it from the scripts directory itself?

**Comment by peterchabs** [comment]
@wellington1092 Execute everything through WinPython Command Prompt
pip3 install -U -r requirements.txt
pip3 install mysqlclient
create_db.py

**Comment by wellington1092** [comment]
C:\Users\Suporte-06\Documents\Monocle-develop (2)\Monocle-develop>python scripts/create_db.py
Traceback (most recent call last):
  File "scripts/create_db.py", line 9, in <module>
    from monocle.db import Base, _engine
  File "C:\Users\Suporte-06\Documents\Monocle-develop (2)\Monocle-develop\monocle\db.py", line 12, in <module>
    from . import bounds, spawns, db_proc, sanitized as conf
  File "C:\Users\Suporte-06\Documents\Monocle-develop (2)\Monocle-develop\monocle\spawns.py", line 9, in <module>
    from .shared import get_logger
  File "C:\Users\Suporte-06\Documents\Monocle-develop (2)\Monocle-develop\monocle\shared.py", line 14, in <module>
    ACCOUNTS = load_accounts()
  File "C:\Users\Suporte-06\Documents\Monocle-develop (2)\Monocle-develop\monocle\utils.py", line 290, in load_accounts
    accounts = load_accounts_csv()
  File "C:\Users\Suporte-06\Documents\Monocle-develop (2)\Monocle-develop\monocle\utils.py", line 313, in load_accounts_csv
    accounts[row['username']] = dict(row)
KeyError: 'username'

**Comment by walaoaaa1234** [comment]
```
username,password,provider,model,iOS,id <<<<<<<<<
ash_ketchum,pik4chu,ptc,"iPhone9,1",10.2.1,2fcfb8c40e244be284aa42313c1d8dee
misty,t0g3p1,ptc,,,
brock,0n1x,google,,,
jessie,w0bbuff3t,,,,
```
leave 1st line there @wellington1092
