### ISSUE TITLE
aiopogo==2.0.1 ClientResponseError missing 2 required positional arguments

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#282]
```
[2017-06-08 11:24:37][   ERROR][worker-387] A wild TypeError appeared!
Traceback (most recent call last):
  File "/home/in/pokeminer/monocle/worker.py", line 666, in visit
    return await self.visit_point(point, spawn_id, bootstrap)
  File "/home/in/pokeminer/monocle/worker.py", line 770, in visit_point
    responses = await self.call(request)
  File "/home/in/pokeminer/monocle/worker.py", line 524, in call
    responses = await request.call()
  File "/home/in/lib/python3.5/site-packages/aiopogo/pgoapi.py", line 148, in call
    response = await request.request(parent.api_endpoint, self._req_method_list, position, parent.device_info, parent._proxy, parent.proxy_auth)
  File "/home/in/lib/python3.5/site-packages/aiopogo/rpc_api.py", line 76, in request
    request_proto = await self._build_main_request(subrequests, player_position, device_info)
  File "/home/in/lib/python3.5/site-packages/aiopogo/rpc_api.py", line 234, in _build_main_request
    sig.location_hash, sig.location_hash_by_token_seed, rh = await hashing
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/in/lib/python3.5/site-packages/aiopogo/hash_server.py", line 77, in hash
    raise ClientResponseError(code=resp.status, message=resp.reason)
TypeError: __init__() missing 2 required positional arguments: 'request_info' and 'history'
```

**Comment by evenly-epic-mule** [comment]
```
  File "/home/r10/lib/python3.5/site-packages/aiopogo/rpc_api.py", line 36, in _make_rpc
    async with _sessions.get(proxy).post(endpoint, data=proto.SerializeToString(), proxy=proxy, proxy_auth=proxy_auth) as resp:
  File "/home/r10/lib/python3.5/site-packages/aiohttp/client.py", line 636, in __aenter__
    self._resp = yield from self._coro
  File "/home/r10/lib/python3.5/site-packages/aiohttp/client.py", line 225, in _request
    proxy=proxy, proxy_auth=proxy_auth, timer=timer)
  File "/home/r10/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 102, in __init__
    self.update_proxy(proxy, proxy_auth, proxy_from_env)
TypeError: update_proxy() takes 3 positional arguments but 4 were given
```
next bug if having proxys enabled

**Comment by Noctem** [comment]
Noctem/aiopogo@46bfab85b4b1dba253570d13c1fb9c68ac2ed09c should fix the first error.

I don't understand how the second one occurred. `update_proxy` is only being called from within aiohttp, and [it does take 4 positional arguments](https://github.com/aio-libs/aiohttp/blob/v2.1.0/aiohttp/client_reqrep.py#L296).

**Comment by evenly-epic-mule** [comment]
as stated in #286 the downgrade / pinnging of aiohttp fixed both

**Comment by captainmedic** [comment]
I am also receiving the 2 required positional statement error on latest branch. I am going to attempt the downgrade

**Comment by captainmedic** [comment]
Another comment, this did stop the 2 required positional arguements

**Comment by Noctem** [comment]
aiosocks 0.2.3 fixes the positional arguments error.
