### ISSUE TITLE
too many file descriptors in select

### ISSUE THREAD

**Issue by evilmoses** [Noctem/Monocle#287]
[2017-06-09 09:06:57][   ERROR][cleanup] A wild ValueError appeared during exit!
Traceback (most recent call last):
  File "scan.py", line 210, in main
    LOOP.run_until_complete(launcher)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scan.py", line 141, in cleanup
    LOOP.run_until_complete(wait_for(pending, 40))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

Can anyone save me?! This is happening every 30 minutes or so. Running on windows server 2012 obviously. Is there a fix workaround I can apply to increase the connections?

**Comment by fivestarp1zza** [comment]
Delete the pickles folder, then retry to launch.  For some reason, this feature causes issues.

**Comment by evilmoses** [comment]
Thanks buddy, will try that next time. Out of interest, what is the biggest grid anyone has been able to successfully use ok windows?
