### ISSUE TITLE
Step 7 Error

### ISSUE THREAD

**Issue by Karlos007** [Noctem/Monocle#296]
After running _python3 scripts/scan.py_ I get this error:

ubuntu@ubuntu-01:/media/sf_Shared/Monocle$ python3 scan.py
Process AccountManager-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 505, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 140, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "scan.py", line 193, in main
    manager.start(mgr_init)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 483, in start
    self._address = reader.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scan.py", line 218, in <module>
    main()
  File "scan.py", line 198, in main
    raise OSError('Another instance is running with the same socket. Stop that process or: rm {}'.format(address)) from e
OSError: Another instance is running with the same socket. Stop that process or: rm ./monocle.sock

It's a clean ubuntu and doesn't have any other process opened.
I can't find a solution.

**Comment by MiguelGallegoRO** [comment]
Have you tried remove ./monocle.sock or change the MANAGER_ADDRESS in config.py?

**Comment by Karlos007** [comment]
Thanks, removing the coment on MANAGER_ADDRESS = ('127.0.0.1', 5002) did the trick :)

btw MANAGER_ADDRESS = 'monocle.sock'  didn't work and the hidden file didn't exist.
