### ISSUE TITLE
web.py crashes sometimes if scan.py is restarted

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/Monocle#56]
```
[2017-01-24 15:38:21,526] ERROR in app: Exception on /data [GET]
Traceback (most recent call last):
  File "/home/develop/lib64/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/develop/lib64/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/develop/lib64/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/develop/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/develop/lib64/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/develop/lib64/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web.py", line 78, in pokemon_data
    return jsonify(get_pokemarkers())
  File "web.py", line 204, in get_pokemarkers
    markers.extend(get_worker_markers())
  File "web.py", line 137, in get_worker_markers
    if not worker_dict:
  File "<string>", line 2, in __len__
  File "/usr/lib64/python3.5/multiprocessing/managers.py", line 732, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.5/multiprocessing/managers.py", line 230, in serve_client
    obj, exposed, gettypeid = id_to_obj[ident]
KeyError: '7f3218d192c8'
---------------------------------------------------------------------------
```

**Comment by evenly-epic-mule** [comment]
quickfix PR #71

**Comment by evenly-epic-mule** [comment]
is merged
