### ISSUE TITLE
Getting ImportError: Cannot import name 'config' on file "create_db.py"

### ISSUE THREAD

**Issue by Bowlmaster** [Noctem/Monocle#63]
I have installed Python 3.6 32 bit
I have installed requirements.
When running comman py -3 create_db.py, I am getting the following:

Traceback (most recent call last):
  File "create_db.py", line 3, in <module>
    from pokeminer import db
  File "C:\Users\Lars\Desktop\pokeminer\pokeminer\db.py", line 14, in <module>
    from . import utils
  File "C:\Users\Lars\Desktop\pokeminer\pokeminer\utils.py", line 25, in <module>
    from . import config
ImportError: cannot import name 'config'

Please help, as I am a rookie on Python

**Comment by m3g4mInD** [comment]
@Bowlmaster Send you config file to  ROOTFOLDERMAP/pokeminer/

**Comment by Noctem** [comment]
Yeah, copy your *config.py* file into the *monocle/* directory (or *pokeminer/* pre-rebrand).
