### ISSUE TITLE
DB exception

### ISSUE THREAD

**Issue by eq2kazial** [Noctem/Monocle#88]
Wanted to give a heads up that after commit 83c7a08 I've started having DB exceptions appear in my scan log, like this:
```
[2017-02-06` 15:04:54,754][   ERROR][dbprocessor] A wild DB exception appeared!
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "timestamp_encounter_id_unique"
DETAIL:  Key (encounter_id, expire_timestamp)=(1882564445, 1486422275) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\Monocle\monocle\shared.py", line 185, in run
    session.commit()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 874, in commit
    self.transaction.commit()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 461, in commit
    self._prepare_impl()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 441, in _prepare_impl
    self.session.flush()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2139, in flush
    self._flush(objects)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2223, in _flush
    flush_context.execute()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 389, in execute
    rec.execute(self)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 548, in execute
    uow
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "timestamp_encounter_id_unique"
DETAIL:  Key (encounter_id, expire_timestamp)=(1882564445, 1486422275) already exists.
 [SQL: 'INSERT INTO sightings (pokemon_id, spawn_id, expire_timestamp, encounter_id, normalized_timestamp, lat, lon, atk_iv, def_iv, sta_iv, move_1, move_2) VALUES (%(pokemon_id)s, %(spawn_id)s, %(expire_timestamp)s, %(encounter_id)s, %(normalized_timestamp)s, %(lat)s, %(lon)s, %(atk_iv)s, %(def_iv)s, %(sta_iv)s, %(move_1)s, %(move_2)s) RETURNING sightings.id'] [parameters: {'pokemon_id': 129, 'spawn_id': -1, 'expire_timestamp': 1486422275.378, 'encounter_id': 1882564445, 'normalized_timestamp': 1486422240.0, 'lat': 33.761286, 'lon': -118.196566, 'atk_iv': None, 'def_iv': None, 'sta_iv': None, 'move_1': None, 'move_2': None}]
```

**Comment by evenly-epic-mule** [comment]
are you running multiple instances on the same database?

**Comment by eq2kazial** [comment]
I am not, only one instance using PostgreSQL.

**Comment by kbtbc** [comment]
I'm getting the same error on mysql (and I am running three separate areas on the same database:
```[2017-02-09 09:22:59,850][   ERROR][dbprocessor] A wild DB exception appeared!
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python36\lib\site-packages\MySQLdb\connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Python36\lib\site-packages\MySQLdb\connections.py", line 270, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '1712110777046968567-1486651965' for key 'timestamp_encounter_id_unique'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\temp\pokemongo\pokeminer-Alpharetta\monocle\shared.py", line 171, in run
    db.add_sighting(session, item)
  File "C:\temp\pokemongo\pokeminer-Alpharetta\monocle\db.py", line 448, in add_sighting
    Sighting.encounter_id == pokemon['encounter_id']))
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2778, in scalar
    ret = self.one()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2749, in one
    ret = self.one_or_none()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2719, in one_or_none
    ret = list(self)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2789, in __iter__
    self.session._autoflush()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 1375, in _autoflush
    util.raise_from_cause(e)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 1365, in _autoflush
    self.flush()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2139, in flush
    self._flush(objects)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2223, in _flush
    flush_context.execute()
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 389, in execute
    rec.execute(self)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 548, in execute
    uow
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python36\lib\site-packages\MySQLdb\connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Python36\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Python36\lib\site-packages\MySQLdb\connections.py", line 270, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '1712110777046968567-1486651965' for key 'timestamp_encounter_id_unique'") [SQL: 'INSERT INTO sightings (pokemon_id, spawn_id, expire_timestamp, encounter_id, normalized_timestamp, lat, lon, atk_iv, def_iv, sta_iv, move_1, move_2) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (23, 9411781223343, 1486651965, 1712110777046968567, 1486651920, 34.10473128117596, -84.26026783287557, 3, 14, 15, 225, 13)]```

**Comment by eq2kazial** [comment]
No longer receiving database exceptions after commit 9825f19. Thanks Noctem!

**Comment by eq2kazial** [comment]
No longer receiving database exceptions after commit 9825f19. Thanks Noctem!
