### ISSUE TITLE
Latest Pull -- Instances get stuck in loop on Windows

### ISSUE THREAD

**Issue by kbtbc** [Noctem/Monocle#96]
Moncole now get's stuck in a loop (is essentially frozen). 

This started happening on most all my instances after I pulled the latest updates and run pip3 to install this morning.  At first, it was the ones with the most workers -- but eventually most all of them hit this error now (and then monocle get's stuck in a loop writing this error over and over into the logs-- logs quickly grow to 1G+):

```
[2017-02-11 10:57:34][   ERROR][root] Caught error on run_forever, restarting loop
Traceback (most recent call last):
  File "C:\temp\pokemongo\pokeminer-Alpharetta\scan.py", line 266, in main
    loop.run_forever()
  File "C:\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Python36\lib\asyncio\base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python36\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Python36\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```

It seems there are now not enough threads for the number of file descriptors trying to be handled at once in Windows?

**Comment by Noctem** [comment]
You're hitting the OS' limit for connections. Try installing [pywin32](https://sourceforge.net/projects/pywin32/files/pywin32/) and adding this to config.py:

```python
from win32file import _setmaxstdio
_setmaxstdio(2048)
```
