### ISSUE TITLE
create_db error messages

### ISSUE THREAD

**Issue by eq2kazial** [Noctem/Monocle#98]
Did a clean macOS Sierra install today, installed requirements and optional requirements for Monocle with no issues. When trying to run create_db.py, I now get the following errors:

```
Traceback (most recent call last):
  File "create_db.py", line 3, in <module>
    from monocle import db
  File "/Users/Scott/Monocle/monocle/db.py", line 16, in <module>
    from . import utils, shared, config
  File "/Users/Scott/Monocle/monocle/utils.py", line 17, in <module>
    from pogo_async import utilities as pgoapi_utils
  File "/usr/local/lib/python3.6/site-packages/pogo_async/__init__.py", line 50, in <module>
    from pogo_async.pgoapi import PGoApi
  File "/usr/local/lib/python3.6/site-packages/pogo_async/pgoapi.py", line 35, in <module>
    from pogo_async.rpc_api import RpcApi, RpcState
  File "/usr/local/lib/python3.6/site-packages/pogo_async/rpc_api.py", line 48, in <module>
    from .utilities import to_camel_case, get_time, get_lib_paths, Rand
  File "/usr/local/lib/python3.6/site-packages/pogo_async/utilities.py", line 135, in <module>
    def get_format_time_diff(low, high, ms=True):
  File "/usr/local/lib/python3.6/site-packages/numba/decorators.py", line 151, in jit
    return wrapper(pyfunc)
  File "/usr/local/lib/python3.6/site-packages/numba/decorators.py", line 167, in wrapper
    **dispatcher_args)
  File "/usr/local/lib/python3.6/site-packages/numba/dispatcher.py", line 423, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/usr/local/lib/python3.6/site-packages/numba/targets/registry.py", line 54, in target_context
    return self._toplevel_target_context
  File "/usr/local/lib/python3.6/site-packages/numba/utils.py", line 278, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/numba/targets/registry.py", line 38, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/usr/local/lib/python3.6/site-packages/numba/targets/base.py", line 232, in __init__
    self.init()
  File "/usr/local/lib/python3.6/site-packages/numba/targets/cpu.py", line 42, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/usr/local/lib/python3.6/site-packages/numba/targets/codegen.py", line 479, in __init__
    self._init(self._llvm_module)
  File "/usr/local/lib/python3.6/site-packages/numba/targets/codegen.py", line 495, in _init
    self._mpm = self._module_pass_manager()
  File "/usr/local/lib/python3.6/site-packages/numba/targets/codegen.py", line 535, in _module_pass_manager
    dl.add_pass(pm)
AttributeError: 'TargetData' object has no attribute 'add_pass'
```

Can anyone point me in the right direction of what the issue is?

**Comment by eq2kazial** [comment]
Closing, problem was using newer llvm/llvmlite than 3.8/15.
